CREATE TABLE IF NOT EXISTS "Parts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" varchar(150) NOT NULL,
    "Description" varchar(500) NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "StockQuantity" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "SalesInvoices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "InvoiceNumber" varchar(30) NOT NULL,
    "CustomerProfileId" integer NOT NULL,
    "StaffProfileId" integer NOT NULL,
    "VehicleId" integer NULL,
    "CreatedAt" timestamptz NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    CONSTRAINT "FK_SalesInvoices_CustomerProfiles_CustomerProfileId" FOREIGN KEY ("CustomerProfileId") REFERENCES "CustomerProfiles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SalesInvoices_StaffProfiles_StaffProfileId" FOREIGN KEY ("StaffProfileId") REFERENCES "StaffProfiles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_SalesInvoices_Vehicles_VehicleId" FOREIGN KEY ("VehicleId") REFERENCES "Vehicles" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesInvoices_InvoiceNumber" ON "SalesInvoices" ("InvoiceNumber");

CREATE TABLE IF NOT EXISTS "SalesInvoiceItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SalesInvoiceId" integer NOT NULL,
    "PartId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "LineTotal" numeric(18,2) NOT NULL,
    CONSTRAINT "FK_SalesInvoiceItems_SalesInvoices_SalesInvoiceId" FOREIGN KEY ("SalesInvoiceId") REFERENCES "SalesInvoices" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SalesInvoiceItems_Parts_PartId" FOREIGN KEY ("PartId") REFERENCES "Parts" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_SalesInvoiceItems_SalesInvoiceId" ON "SalesInvoiceItems" ("SalesInvoiceId");
CREATE INDEX IF NOT EXISTS "IX_SalesInvoiceItems_PartId" ON "SalesInvoiceItems" ("PartId");
